apiVersion: v1
kind: ConfigMap
metadata:
  name: fusion-shared-config
  namespace: fusion-prod
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "pgbouncer-pooler.fusion-prod.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fusion_catalog"
  REDIS_HOST: "redis-sentinel.fusion-prod.svc.cluster.local"
  REDIS_PORT: "6379"
  PROMETHEUS_METRICS_ENABLED: "true"
  AUTH_SERVICE_URL: "http://auth-service.fusion-prod.svc.cluster.local:8001"
  ITEMS_SERVICE_URL: "http://items-service.fusion-prod.svc.cluster.local:8002"
  ORDERS_SERVICE_URL: "http://orders-service.fusion-prod.svc.cluster.local:8003"
  NOTIFICATIONS_SERVICE_URL: "http://notifications-service.fusion-prod.svc.cluster.local:8004"
