apiVersion: v1
kind: Namespace
metadata:
  name: fusion-prod
  labels:
    name: fusion-prod
    environment: production
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
